# TECNÓLOGO DE ANÁLISE E DESENVOLVIMENTO DE SISTEMAS - LÓGICA DE PROGRAMAÇÃO E ALGORITMOS 1
# ALUNO: BRUNO C. RODGERS
# DATA: 2024, 2º SEMESTRE
# EXERCÍCIO 5: UMA LOJA TEM 15 CLIENTES CADASTRADOS E DESEJA ENVIAR UMA CORRESPONDÊNCIA A CADA UM DELES ANUNCIANDO UM BÔNUS ESPECIAL. 
# FAÇA UM PROGRAMA QUE LEIA O NOME DO CLIENTE E O VALOR DE SUAS COMPRAS NO ANO PASSADO. 
# CALCULE E MOSTRE UM BÔNUS DE 10% SE O VALOR DAS COMPRAS FOR MENOR QUE R$1.000,00 E DE 15%, CASO CONTRÁRIO.

import os


os.system('cls')

# Título
print('='*70)
print('EXERCÍCIO 5')
print('='*70)